// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FasChevronLeft: typeof import('~icons/fa-solid/chevron-left')['default']
    FasChevronRight: typeof import('~icons/fa-solid/chevron-right')['default']
    FasClock: typeof import('~icons/fa-solid/clock')['default']
    FasEnvelope: typeof import('~icons/fa-solid/envelope')['default']
    FasGasPump: typeof import('~icons/fa-solid/gas-pump')['default']
    FasHome: typeof import('~icons/fa-solid/home')['default']
    FasInfoCircle: typeof import('~icons/fa-solid/info-circle')['default']
    FasMail: typeof import('~icons/fa-solid/mail')['default']
    FasPhone: typeof import('~icons/fa-solid/phone')['default']
    FasQuestionCircle: typeof import('~icons/fa-solid/question-circle')['default']
    FasRandom: typeof import('~icons/fa-solid/random')['default']
    FasTimes: typeof import('~icons/fa-solid/times')['default']
    FasUserFriends: typeof import('~icons/fa-solid/user-friends')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFasHome: typeof import('~icons/fa-solid/home')['default']
    IFaSolidHome: typeof import('~icons/fa-solid/home')['default']
    IFasUse: typeof import('~icons/fa-solid/use')['default']
    IFasUser: typeof import('~icons/fa-solid/user')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Tutorial_1: typeof import('./src/components/tutorial_1.vue')['default']
    Tutorial_2: typeof import('./src/components/tutorial_2.vue')['default']
    Tutorial_3: typeof import('./src/components/tutorial_3.vue')['default']
    Tutorial1: typeof import('./src/components/Tutorial1.vue')['default']
    Tutorial2: typeof import('./src/components/Tutorial2.vue')['default']
    Tutorial3: typeof import('./src/components/Tutorial3.vue')['default']
  }
}

export { }
