// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FasGasPump: typeof import('~icons/fa-solid/gas-pump')['default']
    FasHome: typeof import('~icons/fa-solid/home')['default']
    FasInfoCircle: typeof import('~icons/fa-solid/info-circle')['default']
    FasQuestionCircle: typeof import('~icons/fa-solid/question-circle')['default']
    FasRandom: typeof import('~icons/fa-solid/random')['default']
    FasUserFriends: typeof import('~icons/fa-solid/user-friends')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFasHome: typeof import('~icons/fa-solid/home')['default']
    IFaSolidHome: typeof import('~icons/fa-solid/home')['default']
    IFasUse: typeof import('~icons/fa-solid/use')['default']
    IFasUser: typeof import('~icons/fa-solid/user')['default']
  }
}

export { }
